run:
  go: "1.23"
linters:
  disable-all: true
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  #- containedctx
  - copyloopvar
  - dogsled
  - dupword
  - durationcheck
  #- errcheck
  - errchkjson
  #- gci
  - ginkgolinter
  - goconst
  - gocritic
  #- godot
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  #- gosimple
  - govet
  #- importas
  - ineffassign
  - loggercheck
  - misspell
  #- nakedret
  #- nilerr
  - noctx
  - nolintlint
  - nosprintfhostport
  - prealloc
  #- predeclared
  #- revive
  - rowserrcheck
  - staticcheck
  - stylecheck
  - thelper
  - typecheck
  - unconvert
  #- unparam
  - unused
  - usestdlibvars
  - whitespace
  # Run with --fast=false for more extensive checks
  fast: true
linters-settings:
  gosec:
    severity: medium
    confidence: medium
    concurrency: 8
    # (NOTE)elfosardo: we should try removing this exclude once we bump golangci-lint to 1.61
    excludes:
      - G115
  importas:
    no-unaliased: true
    alias:
    # Kubernetes
    - pkg: k8s.io/api/core/v1
      alias: corev1
    - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
      alias: apiextensionsv1
    - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      alias: metav1
    - pkg: k8s.io/apimachinery/pkg/api/errors
      alias: k8serrors
    - pkg: k8s.io/apimachinery/pkg/util/errors
      alias: kerrors
    - pkg: k8s.io/component-base/logs/api/v1
      alias: logsv1
    # Controller Runtime
    - pkg: sigs.k8s.io/controller-runtime
      alias: ctrl
    # IrSO
    - pkg: github.com/metal3-io/ironic-standalone-operator/api/v1alpha1
      alias: ironicv1alpha1
  nolintlint:
    allow-unused: false
    require-specific: true
  gocritic:
    enabled-tags:
    - experimental
    disabled-checks:
    - appendAssign
    - dupImport # https://github.com/go-critic/go-critic/issues/845
    - evalOrder
    - ifElseChain
    - octalLiteral
    - regexpSimplify
    - sloppyReassign
    - truncateCmp
    - typeDefFirst
    - unnamedResult
    - unnecessaryDefer
    - whyNoLint
    - wrapperFunc
issues:
  exclude-dirs:
  - mock*
  exclude-files:
  - "zz_generated.*\\.go$"
  - ".*conversion.*\\.go$"
  include:
  - EXC0002 # include "missing comments" issues from golangci-lint
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
  - linters:
    - staticcheck
    text: "SA1019:"
  # Dot imports for gomega or ginkgo are allowed
  # within test files.
  - path: test/.*.go
    text: should not use dot imports
  - linters:
    - revive
    text: "exported: exported method .*\\.(Reconcile|SetupWithManager|SetupWebhookWithManager) should have comment or be unexported"
  # NOTE(dtantsur): IronicDatabase is deprecated but our own code still supports it.
  # Remove this exclusion when it's entirely deleted.
  - linters:
      - staticcheck
    text: "SA1019: (metal3api.IronicDatabase|metal3iov1alpha1.IronicDatabase|ironicConf.Spec.DatabaseName) is deprecated"
