apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

# Make the name of this configmap predictable so users can reference it.
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- envs:
  - manager.env
  name: ironic-standalone-operator-config
