---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ironic-metal3-io-v1alpha1-ironic
  failurePolicy: Fail
  name: mutate-ironic.ironic.metal3.io
  rules:
  - apiGroups:
    - ironic.metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ironics
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ironic-metal3-io-v1alpha1-ironicdatabase
  failurePolicy: Fail
  name: mutate-ironicdatabase.ironic.metal3.io
  rules:
  - apiGroups:
    - ironic.metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ironicdatabases
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ironic-metal3-io-v1alpha1-ironic
  failurePolicy: Fail
  name: validate-ironic.ironic.metal3.io
  rules:
  - apiGroups:
    - ironic.metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ironics
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ironic-metal3-io-v1alpha1-ironicdatabase
  failurePolicy: Fail
  name: validate-ironicdatabase.ironic.metal3.io
  rules:
  - apiGroups:
    - ironic.metal3.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ironicdatabases
  sideEffects: None
