name: Functional

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  functional:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - uses: helm/kind-action@v1
      with:
        cluster_name: kind
        config: ./test/kind.yaml
    - name: Prepare tests
      run: LOGDIR=/tmp/logs ./test/prepare.sh
    - name: Run tests
      run: |
        cd test
        . testing.env
        LOGDIR=/tmp/logs go test -timeout 60m
    - name: Collect logs
      run: LOGDIR=/tmp/logs ./test/collect-logs.sh
      if: always()
    - name: Upload logs artifacts
      uses: actions/upload-artifact@v4
      with:
        name: functional
        path: /tmp/logs/*
      if: always()
