name: Functional Tests

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CLUSTER_TYPE: minikube
      LOGDIR: /tmp/logs
      JUNIT_OUTPUT: /tmp/logs/report.xml
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Setup a minikube cluster
      uses: medyagh/setup-minikube@cea33675329b799adccc9526aa5daccc26cd5052 # v0.0.19
    - name: Prepare tests
      run: ./test/prepare.sh
    - name: Run tests
      run: ./test/run.sh
    - name: Collect logs
      run: ./test/collect-logs.sh
      if: always()
    - name: Upload logs artifacts
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: functional
        path: /tmp/logs/*
      if: always()
    - name: Annotate failures
      uses: mikepenz/action-junit-report@97744eca465b8df9e6e33271cb155003f85327f1 # v5.5.0
      with:
        annotate_only: true
        report_paths: /tmp/logs/report.xml
      if: always()
