name: Functional Tests

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest-4-cores
    env:
      CLUSTER_TYPE: minikube
      LOGDIR: /tmp/logs
      JUNIT_OUTPUT: /tmp/logs/report.xml
    strategy:
      matrix:
        include:
          - name: "upgrade"
            label_filter: "upgrade"
          - name: "regular"
            label_filter: "!upgrade"
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Setup a minikube cluster
      uses: medyagh/setup-minikube@cea33675329b799adccc9526aa5daccc26cd5052 # v0.0.19
      with:
        start-args: "--ha"
    - name: Prepare tests
      run: ./test/prepare.sh
    - name: Run tests
      run: ./test/run.sh
      env:
        LABEL_FILTER: "${{ matrix.label_filter }}"
    - name: Collect logs
      run: ./test/collect-logs.sh
      if: always()
    - name: Upload logs artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: functional-${{ matrix.name }}
        path: /tmp/logs/*
      if: always()
    - name: Annotate failures
      uses: mikepenz/action-junit-report@65fe03598d8d251738592a497a9e8547a5c48eaa # v5.6.0
      with:
        annotate_only: true
        report_paths: /tmp/logs/report.xml
      if: always()
